openapi: 3.0.1
info:
  title: git2consul
  x-cortex-git:
    github:
      repository: life360/git2consul
  x-cortex-tag: git2consul
  x-cortex-groups:
  - compass_type:service
  x-cortex-owners:
  - name: Bedrock
    type: group
    provider: CORTEX
  x-cortex-custom-metadata:
    compass_metadata:
      component_id: ari:cloud:compass:b48cf56c-3102-4142-8d15-87111780edd0:component/05c1ced0-1b30-4a92-a3d9-324d73ddf9f8/e9f7e81a-9922-4cd9-b7ee-464d77b43cd8
      component_labels:
      - name: csv-import
      component_typeId: SERVICE
      component_ownerId: ari:cloud:teams::team/4966b2ca-efa3-4bfc-9760-38a50f074a24-116
